import type { Metadata } from "next";
import { OfferDetailPage } from "@/components/prestations/OfferDetailPage";
import { getProductBySlug } from "@/lib/services/catalog";

export const metadata: Metadata = { title: "Conception installation électrique van, camping-car ou bateau", description: "FabSystem conçoit le cahier des charges, le schéma électrique et la liste d'achat de votre installation embarquée.", alternates: { canonical: "/prestations/conception-electrique" } };

export default async function ConceptionElectriquePage() {
  const product = await getProductBySlug("accompagnement-conception-complete");
  return <OfferDetailPage eyebrow="Conception complète" title="Votre installation conçue de A à Z avant le premier câble." description="Vous expliquez votre usage et vos contraintes. FabSystem prépare le cahier des charges, l'architecture, le schéma et une liste d'achat structurée." price="499 €" priceNote="Tarif de lancement, réservé aux premiers projets conçus par FabSystem." ctaLabel="Ajouter la conception au panier" ctaHref="/contact" purchaseProductId={product?.id} serviceType="Conception d'installation électrique embarquée" faq={[{ question: "Que reçoit-on avec la conception complète ?", answer: "Un cahier des charges, une architecture, un schéma dans l'éditeur et une liste d'achat structurée." }, { question: "Les prix de la liste d'achat sont-ils garantis ?", answer: "Non. Les prix sont observés au moment de la préparation ; les stocks et tarifs fournisseurs peuvent évoluer." }, { question: "Mon projet est-il éligible au forfait ?", answer: "Les projets hors standard ou très complexes sont étudiés avant commande afin de confirmer le périmètre." }]} summary={["Cahier des charges", "Schéma dans l'éditeur", "Liste d'achat structurée"]} imageSrc="/images/prestations/conception-electrique-illustration.jpg" imageAlt="Dossier de conception électrique avec schéma et liste d'achat" forWhom={["Vous partez d'une idée ou de besoins, sans architecture arrêtée", "Vous préférez déléguer la conception plutôt que réunir seul toutes les décisions", "Vous voulez acheter sur la base d'un dossier technique cohérent"]} deliverable="Un cahier des charges validé, un schéma FabSystem prêt à lire dans l'éditeur, et une liste d'achat structurée avec références, quantités et prix constatés." promise="Recevoir une base technique cohérente pour acheter et réaliser votre installation sereinement." steps={[{ title: "Nous cadrons", text: "Nous recueillons vos besoins et validons les hypothèses du projet." }, { title: "Nous concevons", text: "Nous proposons l'architecture, le dimensionnement et le schéma." }, { title: "Nous livrons", text: "Vous recevez le dossier technique et une liste d'achat claire." }]} included={["Entretien de cadrage et cahier des charges", "Architecture et dimensionnement proposés", "Création du schéma dans l'éditeur", "Liste d'achat avec références, quantités et prix observés", "Une phase de corrections mineures", "Un code pour recevoir l'e-book de schéma gratuitement", "12 mois d'accès à l'éditeur inclus"]} boundaries={["Pas de fourniture ou de pose de matériel", "Prix et stocks fournisseurs non garantis", "Changement majeur après cadrage hors forfait", "Projet hors standard : étude personnalisée avant commande"]} />;
}
