import type { Metadata } from "next";
import { OfferDetailPage } from "@/components/prestations/OfferDetailPage";
import { getProductBySlug } from "@/lib/services/catalog";

export const metadata: Metadata = { title: "Accompagnement installation électrique van, camping-car ou bateau", description: "90 jours d'accompagnement pour vérifier vos choix, corriger votre schéma électrique et avancer sur votre projet embarqué.", alternates: { canonical: "/prestations/accompagnement-guide" } };

export default async function AccompagnementGuidePage() {
  const product = await getProductBySlug("accompagnement-guide");
  return <OfferDetailPage eyebrow="Accompagnement guidé" title="Vous construisez. Nous sécurisons les décisions importantes." description="Vous préparez vos besoins, calculs et matériel dans FabSystem. Nous vérifions la cohérence, corrigeons le schéma et vous accompagnons aux jalons importants." price="199 €" priceNote="Tarif de lancement, réservé aux premiers projets accompagnés." ctaLabel="Ajouter l'accompagnement au panier" ctaHref="/contact" purchaseProductId={product?.id} serviceType="Accompagnement de projet électrique embarqué" faq={[{ question: "Quelle est la durée de l'accompagnement ?", answer: "Le forfait couvre 90 jours, adaptés au rythme raisonnable de votre chantier et à ses jalons définis." }, { question: "Comment échangeons-nous pendant le projet ?", answer: "Un groupe WhatsApp dédié et des visios planifiées permettent de suivre les étapes importantes." }, { question: "Le schéma est-il inclus ?", answer: "Nous corrigeons votre schéma. Sa mise au propre complète peut être ajoutée en option à 99 euros." }]} summary={["Un projet défini", "90 jours d'accompagnement", "Groupe WhatsApp et visios planifiées"]} imageSrc="/images/prestations/accompagnement-guide-illustration.jpg" imageAlt="Préparation d'un câblage de van avec accompagnement vidéo" forWhom={["Vous avez fait ou pouvez faire le travail amont dans FabSystem", "Vous voulez réaliser vous-même sans rester seul aux étapes sensibles", "Vous souhaitez faire vérifier vos choix avant que l'erreur ne coûte du temps ou du matériel"]} deliverable="Un projet suivi dans FabSystem, un schéma corrigé, des consignes à chaque jalon et un interlocuteur qui connaît votre installation pendant le chantier." promise="Un projet clair, un schéma corrigé et des validations quand l'erreur coûte le plus cher." steps={[{ title: "Vous préparez", text: "Besoins, calculs, photos et matériel sont renseignés dans votre projet." }, { title: "Nous cadrons", text: "Nous vérifions les choix et corrigeons le schéma existant." }, { title: "Vous réalisez", text: "Nous validons les étapes avant câblage puis mise sous tension." }]} included={["Analyse des besoins, calculs et matériel renseignés", "Avis et corrections sur votre schéma", "Jalons : architecture, avant câblage, avant mise sous tension", "Groupe WhatsApp dédié et visios lorsque nécessaires", "Option mise au propre du schéma : 99 €", "Un code pour recevoir l'e-book de schéma gratuitement", "12 mois d'accès à l'éditeur inclus"]} boundaries={["Création complète du projet non incluse", "Projet limité au périmètre défini au départ", "Pas de support urgent ni de disponibilité permanente", "Pas d'achat, pose ou garantie du matériel"]} />;
}
